### ISSUE TITLE
Past partners in mobile

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#12]
In mobile, the past partner logos get really small. Instead, could we reduce the amount (just show 6) and only show two across the width? 

ex:
Wuxi             J&J
MGH          NIH
Partners    Walgreens

We could check with Jon about which would be the best to show.

**Comment by craigmcginley** [comment]
Finished adjust styles to only show 2 across on mobile, 4 on tablet, 5 on desktop.

Keeping issue open until we confirm with Jon which ones to keep when whittled down, and balance the weight of the logos.

**Comment by sel2sm** [comment]
@craigmcginley here are the 8 Jon selected for mobile: 
3M, BD, Johnson and Johnson, Mount Sinai, WuXi NextCODE, NIH, Walgreens and Partners

Let me know if that creates an unbalanced look and we can reorder the desktop order.

**Comment by craigmcginley** [comment]
done in 68e4d46c32321e08ea97ce66ab23838a161825bf
