### ISSUE TITLE
Add padding

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#13]
<img width="1440" alt="screenshot 2018-09-24 16 25 14" src="https://user-images.githubusercontent.com/20907762/45977085-80f2a800-c016-11e8-92d6-228cd3fca93c.png">

Could we add more space (~20px or so) above and below this text? I see this in a few places across the website -> a few sections are a little scrunched like this. They just need a bit more padding above and below

**Comment by craigmcginley** [comment]
Any other examples? I didn't see others, searching by class name.

**Comment by sel2sm** [comment]
@craigmcginley will we be able to increase the spacing across the website as we discussed earlier? I think it'll make a big difference!

**Comment by craigmcginley** [comment]
done in 8852c69a6841254a40f471316ce87c69a055b6c2
