### ISSUE TITLE
Finding some 404 errors

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/goinvo.com-2018#141]
This is based on stats from Google Webmaster Tools that is identifying times when a 404 page is hit and its corresponding URL.

https://www.goinvo.com/images/features/careplans/CarePlans_Whitepaper_Involution_Studios.pdf
https://www.goinvo.com/boston-is-a-hub-of-marketing-software-the-next-big-tech-sector/
https://www.goinvo.com/involution%E2%80%99s-arlington-visual-budget-wins-mma-innovation-award/
https://www.goinvo.com/blog/2013/03/helping-hires-excel/
https://www.goinvo.com/blog/2012/07/applying-facio-behavioural-part-1-self-satisfaction-2/
https://www.goinvo.com/blog/2012/07/on-thinking-and-feeling/
https://www.goinvo.com/blog/2012/08/applying-facio-behavioural-part-3-behavioural-gap-2/
https://www.goinvo.com/index.php/
https://www.goinvo.com/blog/2013/06/transparency-real-and-contrived/
https://www.goinvo.com/healthcare/diabetes/
https://www.goinvo.com/work/affinnova/
https://www.goinvo.com/healthcare/segterra
https://www.goinvo.com/work/dnc
https://www.goinvo.com/old/images/features/an-oral-history/10-the_box_exercise.pdf
https://www.goinvo.com/what-the-ipad-retina-display-means-for-designers
https://www.goinvo.com/blog/2012/11/being-mindful-and-present
https://www.goinvo.com/healthcare/enterprise
https://www.goinvo.com/blog/2012/10/living-is-growing
https://www.goinvo.com/blog/2013/01/getting-a-better-start-introduction
https://www.goinvo.com/blog/2012/11/virtues-of-friction/
https://www.goinvo.com/images/features/zika/understanding_zika.pdf
https://www.goinvo.com/involution-principal-discusses-design-for-emerging-technology-on-oreilly-radar-podcast/
https://www.goinvo.com/work/numera-social-health

**Comment by craigmcginley** [comment]
looks like I got all of these in: 26c160f7b5b9ea9d835c346d1931ead3150ea2fb
