### ISSUE TITLE
Making hero images taller

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#19]
After playing around with the website more... I'm hoping we could adjust the dimensions of the hero images from 1280 X 175 to **1280 X 320**

Sorry for the late change... they are just feeling a bit too scrunched.

**Comment by craigmcginley** [comment]
@sel2sm they never render 175 height, but always 300px actually except the homepage which is generally taller. Where are you seeing this?

**Comment by sel2sm** [comment]
oh my bad - I was going off of the dimensions in the design, which I think were actually 275 not 175... eh. Either way - could we make the height a bit taller? 320 may still work?

**Comment by craigmcginley** [comment]
Fixed in 17d4680

Bumped up to 325px height on desktop. (275px on mobile).
