### ISSUE TITLE
Mobile buttons should take up full width

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#24]
![image from ios 1](https://user-images.githubusercontent.com/20907762/46160300-5429d500-c250-11e8-9876-76da8dc68e5f.png)

Some buttons don't take up the full width in mobile - they probably all should.

**Comment by craigmcginley** [comment]
Yeah this whole container was a little messed up. Fixed in 36a4089dab9463010820959db3e571aadd86b8c8.

I browsed through the site and didn't notice any others like that.
