### ISSUE TITLE
Remove form field rounded corners (?)

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#25]
Can we get the form field and buttons to match our regular buttons? The regular buttons have right angles whereas the form has rounded ones. Not sure if this is an easy/possible fix....

**Comment by craigmcginley** [comment]
Where? You mean just the "upload resume" input?

**Comment by sel2sm** [comment]
![image from ios 3](https://user-images.githubusercontent.com/20907762/46174178-4d15bd80-c276-11e8-9a82-9524e4079844.png)
In mobile it shows up like this

**Comment by craigmcginley** [comment]
Thanks. I didn't notice that. Will check it out.

**Comment by sel2sm** [comment]
Thanks! It might just be a weird safari thing... it doesn't do that on my comuter

**Comment by craigmcginley** [comment]
Fixed in:
a8f0a95d4b66098208e03b88d3b05a070322e2b6
038694d46b9d25f7031c49be25b5643060cc96f5
b2fb1818a9919895855235c6c55cb0e169381927

lol
