### ISSUE TITLE
Contrain nav on larger screens

### ISSUE THREAD

**Issue by BrysonWong1** [goinvo/goinvo.com-2018#38]
![screen shot 2018-10-10 at 11 35 14 am](https://user-images.githubusercontent.com/31223851/46748013-a15e6b80-cc80-11e8-85ab-2a55d1d1668b.png)
logo in nav lacks constraints

**Comment by BrysonWong1** [comment]
![screen shot 2018-10-10 at 11 40 11 am](https://user-images.githubusercontent.com/31223851/46748315-4a0ccb00-cc81-11e8-83ba-02550df9decd.png)

**Comment by craigmcginley** [comment]
The design does not have it constrained. Are you suggesting it should be constrained to the max width of the content area?

**Comment by BrysonWong1** [comment]
I think it'd look a bit better constrained, though open to pros and cons of that choice.  Also it may help to constrain the photos that are not the hero image ( ie beth and jen on the phone in the image above)

**Comment by craigmcginley** [comment]
I'd bring it up with the other designers before we take any engineering effort. Those half-page-stretch bg images took some trickery to make >_<. Also keep in mind, most folks don't have super wide browser windows on super wide screens.

**Comment by BrysonWong1** [comment]
Okay sounds good. Maybe something for after launch
