### ISSUE TITLE
Home- "Read the case study" missing link

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#39]
On the home page at the top, we need to link up the SNAP case study. Case study should be live soon - this is just a reminder to add that link. 

Wikipedia link also needs to be linked. I'm pretty sure it's this: https://en.wikipedia.org/wiki/Social_determinants_of_health

**Comment by craigmcginley** [comment]
Done in 20931438810f37b7956412a75d210d39c2a79874
