### ISSUE TITLE
Home - "Past partners"

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#40]
Need to add the title "Past partners" right above the logos for our past partners in our Home page. You can check design (I finally updated it). I've got it as H4 within the grey strip.

**Comment by ericbenwa** [comment]
"Past"... ? ... makes it sound like we're done working with them... old/stale... not sure we want to give that vibe.

"Partners", "Our Partners", "We've partnered with many leading organizations", "We've partnered with bleeding edge startups to proven powerhouses in healthcare."
.... a better one = ?

**Comment by craigmcginley** [comment]
done in b2ecdec749ed27fc879be5d7497b986c9e7f6984
