### ISSUE TITLE
About page- "why we cook and eat together 

### ISSUE THREAD

**Issue by BrysonWong1** [goinvo/goinvo.com-2018#41]
Remove link and replace with text
"We cook for one another and share meals together. Cooking and eating as a tribe makes us a closer, better tribe."

**or**
 replace with link to "Print Big" Feature  and add a snippet from the beginning of print big

**Comment by craigmcginley** [comment]
Done. I used print big since the "card" style is always a link, and it would look odd with two cards then one not. Or three cards but one does not link anywhere.

Also I fixed the other two there which were also broken.
