### ISSUE TITLE
Extra line in  SHR case study

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#47]
Could we remove the last heartbeat line at the end of the results section? The background changes from white to grey so it feels odd to have an extra line in there as well. Plus we don't have line after the results section when it's numbers based.

**Comment by jen-p** [comment]
Do we want to remove the closing heartbeat line in all case studies then? Because they all have a final divider at the end

**Comment by sel2sm** [comment]
Yeah I think so - it would be more consistent with the Numbers Results version plus it seems a little extraneous right before the break.

**Comment by jen-p** [comment]
committed something
