### ISSUE TITLE
Case Study Buttons

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#48]
The case study buttons for a few case studies, including SHR and Health Data Basics, are right next to each other horizontally without any padding. Can we add padding horizontally or just have one above the other? 

Additionally, these buttons open the link in the same page. Could we have the button open the link in a new tab?

**Comment by jen-p** [comment]
Fixed margin, new tab + committed
- SHR
- SNAP (added button)
- hGraph
- fasterCures
- inspiredEHRs
- pgp (added button)
