### ISSUE TITLE
Switch out photo

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#50]
In Wuxi Next Code, can we switch the photo of the patient and the ipad to this one: https://www.dropbox.com/s/o3rmcnt0hmi7yux/DSC_4274.jpg?dl=0

**Comment by sel2sm** [comment]
@jen-p in the Wuxi Next Code case study, the heartbeat line should also go before Results section and not after that last section.

**Comment by jen-p** [comment]
committed
