### ISSUE TITLE
Infobionic Preview Image

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#54]
I think it would make more sense for this screen to show up in a clinical environment. Reading the case study, I think it's about doctors monitoring the cardiac arrhythmias rather than patients monitoring it.. soooo could we remake this cover image with this clinical stock photo? 

https://www.dropbox.com/home/Graphics/resources/photos-stock_devices/healthcare_environments?preview=DSC_4226.jpg

(not sure who made the current one - maybe Jen or Parsuree can help with this)
thanks!

**Comment by jen-p** [comment]
committed change
