### ISSUE TITLE
Switch Killer Truths photo

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#71]
Could you switch the Killer Truths photo with this one? https://www.dropbox.com/s/wj62vnbvws1fv5b/killer_truths_cover.jpg?dl=0 

It's still not amazing, but I think this one won't get cropped oddly.

**Comment by jen-p** [comment]
swapped and committed

**Comment by craigmcginley** [comment]
done in eff69f0581c2e9e72ec0cac367313db10da90efe
