### ISSUE TITLE
Banner bug in Killer Truths

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#76]
Weirdly only in Killer Truths (that I've found so far), the Contact button in the banner is not centered vertically. 
<img width="1280" alt="screenshot 2018-10-15 17 57 28" src="https://user-images.githubusercontent.com/20907762/46980880-ff85b700-d0a3-11e8-9738-68e378f06ec5.png">

**Comment by craigmcginley** [comment]
Fixed in 50a11efd127f00a166dc19c6569bc6c7409c3701
