### ISSUE TITLE
Sharon's LinkedIn lol

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#77]
Link appears to be broken. Here's the correct link: https://www.linkedin.com/in/sharon-lee-a1371999

**Comment by sel2sm** [comment]
Also, could you be sure it opens in a new tab? I think it's opening in the same right now.

**Comment by craigmcginley** [comment]
Fixed in 5fb326508cda566829c8e21bd183929073927ab0

So sorry Sharon!
