### ISSUE TITLE
hGraph cover image

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#82]
I know we're waiting for a new version of the hGraph (@ericbenwa you still working on that?)

But in the mean time, I had already made this one for potentially using as our home page image before! https://www.dropbox.com/s/1dbwvve7ef2ujn2/hgraph_cover.jpg?dl=0

**Comment by jen-p** [comment]
committed

**Comment by craigmcginley** [comment]
done in 9ec1b14438774a63f09fca36e48c6a72d27176de
