### ISSUE TITLE
"Visits per month today"

### ISSUE THREAD

**Issue by jsonin** [goinvo/goinvo.com-2018#86]
Results section with 
"600 visits / month today"
https://www.goinvo.com/work/inspired-ehrs

visits today or per month?

**Comment by sel2sm** [comment]
Additionally, could we include "View the book" button with a link to the book here at the bottom? We have the space (there's only 2out of 3 results)!

<img width="1280" alt="screenshot 2018-10-15 21 50 18" src="https://user-images.githubusercontent.com/20907762/46987950-5a2f0b00-d0c4-11e8-8c13-20095e35f7f1.png">

**Comment by jsonin** [comment]
Yes! "Read the Book" link on the bottom.

**Comment by jen-p** [comment]
It's just going to show up as part of the results section or below because of how the case study layout is set up

![screen shot 2018-10-16 at 10 27 46 am](https://user-images.githubusercontent.com/1414310/47023745-4b7d3e00-d12e-11e8-9911-b32900294255.png)

**Comment by jen-p** [comment]
Committed, will mark to merge if this looks good @sel2sm @jsonin

**Comment by craigmcginley** [comment]
done in fa67c9fecb9b56e7b94a652b315708defdbeb312
