### ISSUE TITLE
Bathroom to Healthroom incorporated or not?

### ISSUE THREAD

**Issue by sel2sm** [goinvo/goinvo.com-2018#88]
When you click on the case study from work, it opens in a new tab. When you click on it from the Services page under Emerging Technologies, it opens in the same one. 

It would be ideal to reformat it into our current design and add Up Next section... but until then it's probably good to open a new tab and be consistent.

**Comment by craigmcginley** [comment]
Made all features (+ any page that has new goinvo.com header/footer) open in same tab, as agreed upon in Slack.

Done in 314703b1390dca7d6960228dc4c6d3848a23cb39
