### ISSUE TITLE
Sad, lonely avatar on homepage / DoH video never loads on mobile

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/goinvo.com-2018#96]
The DoH video never loads on the homepage for me.
iPhone 6, Safari.

![img_1615](https://user-images.githubusercontent.com/983918/47021283-1fab8980-d129-11e8-847c-ce609b202f15.PNG)

**Comment by craigmcginley** [comment]
This happens in Safari mobile  + desktop, as far as I can tell.

These are the closest leads I have so far:
- https://stackoverflow.com/questions/32996396/safari-9-0-can-not-play-mp4-video-on-the-storage-server
- https://github.com/facebook/create-react-app/issues/3082

Gatsby uses PWA techniques with a service worker. I've tested with videos from an external source and those seem to do fine. So it's something about our s3/cloudfront distribution interacting with the service worker + byte range requests, or possibly the caching of service-worker files. Still investigating...

**Comment by craigmcginley** [comment]
This should be fixed now in 7863962bd9a35c26f79b9436f6abd564dc499b5e. All my testing shows it working. If there are issues noticed again, reopen this issue.
