### ISSUE TITLE
To capitalize or not on work categories... ?

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/goinvo.com-2018#97]
Patient Engagement is Title Case but the other are not.
Which treatment stays?

![img_1617](https://user-images.githubusercontent.com/983918/47021774-17078300-d12a-11e8-9524-7a78d2d322b9.PNG)

**Comment by jen-p** [comment]
committed

**Comment by craigmcginley** [comment]
done in f786a9f3b1b69a64dd6c93e7bfaaadc6e5e5dc3b
