### ISSUE TITLE
Why 'projects' label for Open Source... ?

### ISSUE THREAD

**Issue by ericbenwa** [goinvo/goinvo.com-2018#98]
Doesn't every category contain 'projects'? 
Why specifically call it out for Open Source to include 'Projects'?

![img_1617](https://user-images.githubusercontent.com/983918/47021961-8e3d1700-d12a-11e8-8f43-147d3abcc57b.PNG)

**Comment by jen-p** [comment]
committed

**Comment by craigmcginley** [comment]
done in f786a9f3b1b69a64dd6c93e7bfaaadc6e5e5dc3b
